### ISSUE TITLE
Consider running CI actions on all branches and PRs - not just those that merge to main

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#123]
When creating a new project from scratch copier initializing git with a default branch name specified by git's `init.defaultBranch` setting ("master" if not specified). However most of template's Github Actions workflows use "main" branch.

Generally speaking, it is unclear for me why testing and linting are not being applied to all branches.

**Comment by drewoldag** [comment]
Thanks for the note, you're correct that the latest tagged release of the copier template defaults to 'master'. However, we have a change staged that will change that to default to 'main', we just haven't tagged it for release yet :) 


Your second point about testing and linting being applied to all branches is a valid question. As it stands, I believe all of the CI automation will run when a user creates a PR that will merge into main - which we take to be the "standard" work flow. 

However, I don't think there is a reason to restrict it to just PRs that will merge to main. If it's ok with you, I'll rename this ticket to reflect that as the primary request.

**Comment by drewoldag** [comment]
General consensus is that we'll leave this as is, with the understanding that we're supporting a "typical use case". Hydrated projects can, of course, modify the CI action triggers as needed. And when users update their projects from the template, they have the option of excluding changes to the CI actions that would overwrite their customizations.

**Comment by hombit** [comment]
For me it looks like it probably was fixed even before I wrote this issue, in e4ddc2b1be538772dad07f2f3cd30e8378e1546c, so sorry for the confusion
