### ISSUE TITLE
Recommend users pre-commit.ci 

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#135]
pre-commit.ci is a CI service running pre-commit hooks - and committing fixes to open PRs. It also keeps `.pre-commit-config.yaml` updated sending new PRs to bump individual hook versions. pre-commit.ci requires no additional configuration - just `.pre-commit-config.yaml`. I suggest updating docs to recommend it for users.

**Comment by henryiii** [comment]
I do this in https://scikit-hep.org/developer/style
