### ISSUE TITLE
Don't ask questions all over again when updating

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#139]
When you run copier again to update, you have to click through all the same questions again.

As a user, I get kind of blind to this process, and assume that I'm approving everything I've selected previously, and just smash enter the whole way through.

Could we have some option to only ask new questions (e.g. those we don't already have an answer in copier-answer.yml), when updating?

```
>> Would you like to use simple (default tooling) or customized installation?
       customized
       simple
    >> use previous answers
```

**Comment by drewoldag** [comment]
We should just take the time to figure out if this is possible with Copier or not.

**Comment by jeremykubica** [comment]
I haven't found a good way of doing this. The best option I have found so far is to use -f to use previous answers or defaults for new questions.

**Comment by drewoldag** [comment]
Ok, thanks for taking a look at this. I've thrown the ball over the fence to the copier folks by creating this feature request: https://github.com/copier-org/copier/issues/1178
