### ISSUE TITLE
Investigate automatically using codecov for CI

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#14]
Can we implement this without needing an api key? If we do should we just leave instructions for the users?

**Comment by smcguire-cmu** [comment]
For public repos a token is not needed, but the user does have to login to the Codecov website with their GitHub account, and add the [Codecov GitHub integration](https://github.com/apps/codecov) to their repo.

I don't think we can automate these steps, and they need the repo to be created on GitHub before they can be done. Perhaps we could add a step into the copier asking if they want to add the Codecov integration? Then if they input yes we add steps giving them the links to the login and integration, and add the upload step to the action.

**Comment by smcguire-cmu** [comment]
Alternatively, we could just leave it as instructions with the links and the YAML to add the step the action
