### ISSUE TITLE
Update readthedocs to include versioned documentation

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#145]
Currently we have "stable" and "latest", but it might be nice to include versioned documentation material as well.

**Comment by drewoldag** [comment]
I believe this refers to the RTD for the template itself.

**Comment by delucchi-cmu** [comment]
RTD holds on to the built documentation for each tagged release, and we can manually "activate" versions that will appear in the lower-left-hand version menu. I've enabled the most recent handful of versions, so we can use them if we want. There does not appear to be a mechanism to automagically activate a versioned document set when it is no longer either the "latest" or "stable" doc, but if we want to retrieve the older documentation, any admin for the RTD site can activate that version (myself, Drew, or Carl).
