### ISSUE TITLE
The regex validation for project and module name don't match tooltip text

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#147]
@OliviaLynn  pointed out the following:
The regex for the project name correctly allows for upper and lower case letters, but the tooltip says "all letters lowercase". We should remove the "all letters lowercase" part.

The regex for module name allows for uppercase letters, but should not. 
The current regex: `^[a-zA-Z][a-zA-Z0-9\_]+$`
Should be changed to: `^[a-z][a-z0-9\_]+$`

**Comment by OliviaLynn** [comment]
Didn't catch this issue in time to include it in #141, so addressed it in a new PR.
