### ISSUE TITLE
Consider MyPy for static type hint checking

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#15]

**Comment by smcguire-cmu** [comment]
We can add a separate CI action to check any type hints with mypy. It will ignore any code written that's not had type hints added, so it should pass if people want to write code without type hints (Though it can be set to force having type hints). 

The only problem for people that don't want to use type hints is imports. By default, mypy will give an error if a package is imported that doesn't have any type hints. These can be suppressed, but if it finds a package that has type hints that need to be installed as a separate package, it will still throw an error and tell the user to install the type hints. I don't think there is a way to ignore these errors.

This could be confusing for any users that don't want to use type hints, so we probably don't want this to be included by default. If we can with copier, we could add an option to include it or not?
