### ISSUE TITLE
Move documentation build out of unit test and coverage workflow

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#151]
It probably makes sense to move the doc building workflow into it's own workflow. It's currently included in the unit test and coverage workflow, that runs over python 3.8-3.10. 

I don't immediately think that it's valuable to ensure that it builds on all those versions of python. But I could be wrong there.

**Comment by OliviaLynn** [comment]
Great! I mentioned wondering if maybe it should be taken into its own workflow, back in the first bullet of PR #125, so I appreciate getting an answer here.
