### ISSUE TITLE
Add Ruff Linter option

### ISSUE THREAD

**Issue by smcguire-cmu** [lincc-frameworks/python-project-template#185]
I came across [this linter called Ruff](https://beta.ruff.rs/docs/) the other day, and was amazed at how fast it ran, practically instantly on hipscat vs ~10 seconds for pylint. It might be nice to have an option for it.

**Comment by drewoldag** [comment]
That's a good call out @smcguire-cmu and aligns with what was being called out in #122. Let's chat about this, I would like to get your take on it.
