### ISSUE TITLE
Warn if project should be updated

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#19]
Could we, maybe as part of a smoke test, determine if there's a new version of the template a project was based on, and spit out a warning?

Why? I'd want to keep projects from getting stale and getting far behind what we've determined are best practices. 

Alternatively, can we generate a list of projects that have used the template and which version they're updated to, to run `copier update` on them after updating the template version?

**Comment by drewoldag** [comment]
This is an interesting thought. We could add an automated cron job test that could check for the latest revision tag from the template repository and compare it against the current tag in the .copier-answer.yml file - then report that somehow. Emails about failing smoke test???

**Comment by drewoldag** [comment]
It looks like there are a couple of github actions that will use `git describe --tags` to try to determine what the latest tag is for a given repository. So if that works, and we could add a tool that would fetch the latest version of the python-project-template repo, that would be a start. 

Then, in the hydrated project, there is a `.copier-answers.yml` file. The second line of that file is the tag-commit that was used to hydrate the project. 

For instance, if I run `git describe --tags` on the py-proj-template main branch, I get:
`>> v1.2.1-2-gbdfdba9`

In one of my older test project, if I run ` cat .copier-answers.yml | grep _commit | awk '{print $2}'`, I get: 
`>> v1.0.0-3-g3544c4e`

So we could theoretically compare those values in a github action.

**Comment by drewoldag** [comment]
This also seems to do a good job of getting a remote branch's latest tag: 
`git ls-remote --tags --sort=committerdate https://github.com/lincc-frameworks/python-project-template | grep -o 'v.*' | sort -r | head -1`

An open question is whether the other users would be able to issue those commands successfully against the lincc-frameworks project.

**Comment by drewoldag** [comment]
We would want to strike a nice balance here. Avoiding being bothersome but at the same time not being so quiet that the user never notices. 

@OliviaLynn found a couple of github actions on the marketplace that will create Github issues in a repository. So this might be a good way of doing it:

- https://github.com/marketplace/actions/create-an-issue
- https://github.com/marketplace/actions/create-github-issue

Another point to consider is that we would not want to flood the user with issues. So if we place a check in a smoke test run by a cron job, we wouldn't want that cron job to be constantly producing issues until the user updates. We would need some way to check to see if the user has already been notified for a given release, and only ping them again in there is yet another new release. 

i.e. 

1. User creates new project from template version 1.0
2. The template is updated to 1.1
3. The user is notified via cron job
4. cron job runs a bunch more, but don't bug the user again
5. The template is updated to 1.2
6. The user is notified via cron job again.

**Comment by drewoldag** [comment]
Another approach that we could consider is a pre-commit hook. Typically a pre-commit hook will only print output to the screen if there has been a failure. 

However, in "verbose" mode, more output can be printed, even if the hook is passing. 

Thus, we could create a python script that would pull the version of the template used by the project and compare it against the latest tagged release of the template. It would be configured to always pass, but would print out a message about updating the template if a newer tag was available.

**Comment by drewoldag** [comment]
I was able to create a pre-commit hook that I'll push up to a separate LINCC-frameworks repository. I'm testing it locally in my qp_flexzboost directory using the following command:

`pre-commit try-repo ../template-version-check/ check-lincc-frameworks-template-version --verbose`

**Comment by drewoldag** [comment]
Next steps:

- [ ] Create GitHub repo
- [ ] Add some unit tests
- [ ] Add this to the python project template
