### ISSUE TITLE
Investigate using tox for integration tests

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#190]
Currently there isn't a good automated way to test that the template works as expected. We use GitHub automation, but it's pretty slow. 

Perhaps tox could orchestrate integration tests locally.

**Comment by henryiii** [comment]
I do this with nox in https://github.com/scikit-hep/cookie

**Comment by smcguire-cmu** [comment]
I looked into this a bit, and it seems possible to do what we do in the GitHub CI with nox. I was thinking we could have some folders containing test copier configurations and expected file outputs to go through and test with for different python versions, [which nox can do](https://nox.thea.codes/en/stable/tutorial.html#testing-against-different-and-multiple-pythons).

**Comment by henryiii** [comment]
FYI, there's now https://github.com/scientific-python/cookie, with associated development guide and repo-review tool; it's the generalization of scikit-hep/cookie.
