### ISSUE TITLE
Option to enable/disable .pylintrc files

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#194]
I've gotten feedback that some folks would prefer their pylint config in the pyproject.toml file for ease-of-use.

Converting between these setups requires some massaging.

**Comment by drewoldag** [comment]
Also mentioned in issue #205

**Comment by drewoldag** [comment]
This is a good example of when a separate config for tests vs. source is really convenient. So putting things in pyproject.toml is nice, but doesn't distinguish between particular use cases. 

Perhaps we can expand the documentation around this particular feature to explain why we have two pylint.rc files and why we run pylint separately on src and test directories.

**Comment by drewoldag** [comment]
Even though it is likely that we'll create a RAIL-specific version of the python project template, I would advocate that we still take on the two action items in the previous comment. And when a RAIL-specific template is created, then we can default to having the .pylintrc file content in the pyproject.toml file.
