### ISSUE TITLE
test/coverage excluded pattern

### ISSUE THREAD

**Issue by cchris28** [lincc-frameworks/python-project-template#201]
I frequently use unit tests in vscode as a debug and investigative tool and the results while useful are not really unit tests. So I want to put them in a separate folder that is not run automatically.

The current invocation of pytest searches all directories in the project for the test pattern name and runs them both for testing and coverage.

I suggest we have a convention for the --ignore=<name> argument to pytest for test like code that can be run manually but not automatically.

I have been using --ignore=tests/private which makes it show up in vscode as a set of tests (useful for development) and get ignored by pre-commit. Note that pre-commit quiets everything so you normally do not notice that it is picking up ALL files that match the test string.

Possibly we should restrict it to src tests since those are the only source directories we have.

**Comment by drewoldag** [comment]
We can add some documentation to indicate that users can do, i.e. add an `ignore` flag for pytests. 
It would make sense to specify which directory pytest should look in to discover tests.
