### ISSUE TITLE
adapt template for use with python namespace packages

### ISSUE THREAD

**Issue by cchris28** [lincc-frameworks/python-project-template#204]
Packages constructed using this recipe would be installed like:

pip install ppt-foo ppt-bar ppt-blat

And code would import like:

from ppt import foo, bar, blat

We could document this as a recipe for the user. We could also incorporate it into the answers if that seems useful.

PEP 420 introduced namespaces so that organizations with related packages could present them under a common prefix while separately maintaining the contained packages. This is similar in concept to C++ namespaces and share some features. They are open and so the namespace package can be built by composition.

The modifications from a python-project-template created repository are shown below. I did verify that it builds and installs locally. I have yet to run the full suite of tests so there may be other changes involved as well. Nor have I tried to create it on pypi-test.

This assumes that the namespace is "ppt" (python-project-template?).

The first variation exactly maintains the file structure but renames src to the namespace package name, reflects that change pyproject.toml and then add a clause at the end of pyproject.toml to identify this as a subpackage of a namespace package.

mv src ppt
sed <pyproject.toml '/^write_to = /s%src/%ppt/%' > .tmp
cat >>.tmp <<!
[tool.setuptools.packages.find]
where = ["."]
include = ["ppt"]
namespaces = true
!
cat .tmp >pyproject.toml
rm .tmp

The second variation I have similarly verified creates a layer underneath src for the namespace package but otherwise keeps the file structure.

mv src ppt; mkdir src; mv ppt src
sed <pyproject.toml '/^write_to = /s%src/%src/ppt/%' > .tmp
cat >>.tmp <<!
[tool.setuptools.packages.find]
where = ["src"]
include = ["ppt"]
namespaces = true
!
cat .tmp >pyproject.toml
rm .tmp

**Comment by drewoldag** [comment]
This is probably the type of thing that comes up after a project has been around for a while. Often occurs when a project needs to be broken up into logical components. 

If there's an advanced section of the PPT docs - it makes sense to put it there. Perhaps this could be an open discussion as well.

**Comment by drewoldag** [comment]
The general consensus of the group was that this is a valuable tool, but would probably would likely be too complicated for the standard user of the python project template to understand and want to use right away. The hunch is that this is something that a project developer identifies well after a project has started, but perhaps isn't aware of the need from the onset, and occurs after a project has matured to the point that there are logical pieces that need to be broken apart.

Documenting this and adding it to a (perhaps "Advanced") section of the PPT documentation makes sense. Additionally, a tech talk about using `namespaces` to refactor existing code would be quiet engaging. 

@cchris28 would you be interested in taking on either or both of the documentation and tech talk?

**Comment by cchris28** [comment]
sure. assigning this to me. Also a pull request showing the changes I prototyped.
I don't expect we will want to merge but it does show a working implementation and how we might tie in.
Also, wondering if it is possible to set copier variables without a question/answer section? Because then this could be part of the template without affecting users directly.

**Comment by drewoldag** [comment]
I haven't had a chance to look over the PR yet, but I wanted to know more about what you meant when you said "wondering if it's possible to set copier variables without a question/answer section". Could you elaborate on that question a little more?
