### ISSUE TITLE
Stuff I did to use the with rail.

### ISSUE THREAD

**Issue by eacharles** [lincc-frameworks/python-project-template#205]
Used template like so:

```
# Changes here will be overwritten by Copier
_commit: v1.3.4
_src_path: gh:lincc-frameworks/python-project-template
author_email: Later@Later
author_name: Later
create_example_module: false
custom_install: true
include_notebooks: false
mypy_type_checking: none
package_name: rail_dummy
preferred_linter: pylint
project_license: MIT
project_name: rail_dummy
use_gitlfs: none
use_isort: false

```

Removed some stuff:
```
\rm -rf docs   # don't want docs here
\rm src/.pylintrc tests/.pylintrc  # want this in pyproject.toml
\rm tests/rail_dummy/conftest.py  # not used
\rm .readthedocs.yml  # don't want docs here
\rm -rf src/rail_dummy  # namespace, not package
```

Edited pyproject.toml

Changed name
> name = "pz_rail_dummy"   # Might have been able to do this in copier answers, not sure

Removed unwanted deps
<     "ipykernel", # Support for Jupyter notebooks.  
<     "sphinx==6.1.3", # Used to automatically generate documentation
<     "sphinx_rtd_theme==1.2.0", # Used to render documentation
<     "sphinx-autoapi==2.0.1", # Used to automatically generate api documentation

Changed version file location to work with namespace
> write_to = "src/rail/dummy/_version.py"  # namespace

Added pylint and pylint-cov options as I like them
> [tool.pylint]
> disable = [
>     "abstract-method",
>     "invalid-name",
>     "too-many-statements",
>     "missing-module-docstring",
>     "missing-class-docstring",
>     "missing-function-docstring",
>     "too-few-public-methods",
>     "duplicate-code",
>     "use-dict-literal",
>     "broad-exception-caught",
> ]
> max-line-length = 110
> max-locals = 50
> max-branches = 25
> max-public-methods = 50
> max-module-lines = 1500
> 
> 
> [tool.pytest.ini_options]
> addopts = [
>     "--cov=rail",
>     "--cov-report=html"
> ]

**Comment by drewoldag** [comment]
@drewoldag Open a new issue to optionally include documentation generation.

**Comment by drewoldag** [comment]
We have an existing ticket to track moving the location of pylint.rc files #194. Created issue #208 to track the option to exclude all sphinx/readthedocs autodocumentation.

**Comment by drewoldag** [comment]
@cchris28 - interesting to note in the first summary section that Eric had to move the `_version` file around to support `namespace` use case.
