### ISSUE TITLE
Complete Linting - How to modify/remove documentation

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#216]
Currently it is just "TODO"
https://lincc-ppt.readthedocs.io/en/latest/practices/linting.html#how-to-modify-remove

**Comment by Pallavi16d** [comment]
Hi there! I noticed that the "Complete Linting - How to modify/remove documentation" issue mentions "TODO" without any specific instructions. Could you please provide more details on what specific information or steps need to be included in the documentation for modifying or removing linting? With more information, I'll be happy to contribute and update the documentation accordingly. Thank you!

**Comment by drewoldag** [comment]
I think that we might want to break this up in to two sections. 

The first section is "How to modify", with two subsections, one for pylint and one for black. 

The pylint section should direct the user to the .pylintrc files in ./src and ./test as the places to make modifictions, and also include a link to pylint configurations (https://pylint.readthedocs.io/en/stable/user_guide/configuration/all-options.html) so that users know what can be modified.  It would also be nice to include the reasoning behind the choice to have two .pylintrc files outside of the pyproject.toml file - namely that it provides a finer grain of control over pylint and allows different linting rules to be configured for source vs. test code.

The black section should indicate that there really isn't a lot of configuration that can be performed, and provide a link to the Black documentation and configuration section: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html


The second section is "How to remove", and should direct users to modify the copier answers that they selected by running `copier update`. It would be good to be more explicit about the specific copier command. Perhaps `copier update --data preferred_linter=[pylint|black|none]`.
