### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#231]
Add a pull request template **for changes to the python-project-template repo**.

Specifically, add some reminder that this is creating a pull request in the `lincc-frameworks/python-project-template` repository. 

Now that we have several supported forks of the repo, it's a little too easy to accidentally create a pull request against the wrong repo, and github has no plans to set a default repo for pull requests for forked repositories.

**Comment by drewoldag** [comment]
Should add some other checkboxes for the PR template. i.e. does this change require some new CI tests, etc.
