### ISSUE TITLE
Make the python versions configurable

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#246]
Currently, we run all CI/CD actions against python 3.8, 3.9, and 3.10. Not all projects will need to stay compatible with all versions of python (and some may be targeting 3.11!).

We could limit the github workflow action load by reducing the number of python versions supported, and this could be done at project creation time by limiting the versions in the hydrated project.

**Comment by drewoldag** [comment]
This is related to #275
