### ISSUE TITLE
Recursive pylint check isn't really recursive

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#263]
I don't think the current pylint line in the linter workflow does what's intended:

When I run the line from the workflow file on a local directory, I only get warnings from the first level of files (e.g. /src/project/module.py, but not in /src/project/sub/module.py).

```
$ pylint -rn -sn --recursive=y ./src --rcfile=./src/.pylintrc
```

vs what I use locally that gives me errors in subdirectories:

```
$ pylint -rn -sn --rcfile=./src/.pylintrc ./src/
```

**Comment by smcguire-cmu** [comment]
It seems like we can't recreate this bug, and everything looks to be working as it should, so I'm going to close this for now.
