### ISSUE TITLE
Clarify requirement to use `pip -e [dev]` for local development 

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#289]
This is feedback received from a user updating a pre-existing project with the PPT: 

> It wasn't obvious to me at first that in the development environment
> you really have to run pip install -e ".[dev]" for things to commit.

I would guess the difficulty is related to some of the pre-commit checks that run, and perhaps not having, say `black` installed prior to running pre-commit if the `-e [dev]` flag wasn't passed.

**Comment by blanton144** [comment]
That's right. I just at first didn't think to 'pip install' at all before trying to commit, but having a first-time user 'pip install -e ".[dev]"' before even trying to commit would make sure their environment had everything installed for commit.

**Comment by wilsonbb** [comment]
Hi @blanton144, a quick clarifying question:

Do you happen to know what instructions you were following along with?

Were you just following the [Getting Started](https://github.com/lincc-frameworks/python-project-template#getting-started) in the README, or were you following the (Starting a New Project)[https://lincc-ppt.readthedocs.io/en/latest/source/new_project.html] or (Incorporating the template into a prior project)[https://lincc-ppt.readthedocs.io/en/latest/source/existing_project.html] instructions?

**Comment by blanton144** [comment]
It was the "incorporating template into a prior project" ... though now I
see the instructions there! So maybe I missed them before.

On Fri, Nov 3, 2023 at 4:30 PM Wilson Beebe ***@***.***>
wrote:

> Hi @blanton144
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_blanton144&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=u4F0awrEX1HhzbJ0yM3dgpGRPHXrOEE4NK_GVZchv6Tn_IklYrDaDSSjJDEWfzP8&s=p0ckbjM6I8KxHLmOIzJG70hhDoJ11Uhtvy0FASZxOhQ&e=>,
> a quick clarifying question:
>
> Do you happen to know what instructions you were following along with?
>
> Were you just following the Getting Started
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lincc-2Dframeworks_python-2Dproject-2Dtemplate-23getting-2Dstarted&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=u4F0awrEX1HhzbJ0yM3dgpGRPHXrOEE4NK_GVZchv6Tn_IklYrDaDSSjJDEWfzP8&s=ZPy2ywtZdUKeVuKEuylpGe6iaBni3mAE4uOrgBGiP0Y&e=>
> in the README, or were you following the (Starting a New Project)[
> https://lincc-ppt.readthedocs.io/en/latest/source/new_project.html
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__lincc-2Dppt.readthedocs.io_en_latest_source_new-5Fproject.html&d=DwQFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=u4F0awrEX1HhzbJ0yM3dgpGRPHXrOEE4NK_GVZchv6Tn_IklYrDaDSSjJDEWfzP8&s=ZMD8GJt_zxotvE-w5kR9UBF-0vKjyY7sWlIP5SPjgXg&e=>]
> or (Incorporating the template into a prior project)[
> https://lincc-ppt.readthedocs.io/en/latest/source/existing_project.html
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__lincc-2Dppt.readthedocs.io_en_latest_source_existing-5Fproject.html&d=DwQFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=u4F0awrEX1HhzbJ0yM3dgpGRPHXrOEE4NK_GVZchv6Tn_IklYrDaDSSjJDEWfzP8&s=BcdyIax0HN5s5iMeAgjvH69234fmkz-OcvbF_z1KJ94&e=>]
> instructions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lincc-2Dframeworks_python-2Dproject-2Dtemplate_issues_289-23issuecomment-2D1793057773&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=u4F0awrEX1HhzbJ0yM3dgpGRPHXrOEE4NK_GVZchv6Tn_IklYrDaDSSjJDEWfzP8&s=XsSKVhFJnO32Mmr6RQ26mH8QlhRXr7TSTCxq50WKGf0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAODDFR57FTFRCAGOHWSINLYCVH45AVCNFSM6AAAAAA5E5PXHSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTGA2TONZXGM&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2nqg0fcNitaQTtJ4c9MSjg&m=u4F0awrEX1HhzbJ0yM3dgpGRPHXrOEE4NK_GVZchv6Tn_IklYrDaDSSjJDEWfzP8&s=HuQLtIynPBDg4NCH1Z-ZWeRw2rHKTgqmoPLFIJIjU10&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>


-- 
Michael Blanton, Professor
Department of Physics
New York University

**Comment by wilsonbb** [comment]
Ah thanks! If that's the case, I think we can probably close the issue.

The [Starting a New Project](https://lincc-ppt.readthedocs.io/en/latest/source/new_project.html) instructions also have the user run `bash .prepare_project.sh` which runs the `pip` command on the user's behalf.

Feel free to reopen if there's any additional feedback!
