### ISSUE TITLE
Make setuptools-scm optional

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#304]
`setuptools-scm` is great, but there are cases when it becomes very inconvenient to use. My use case is deploying a web-service as a Docker image, and I don't really want `.git` to be in my Docker image.

It is how my `Dockerfile` typically looks like:
```Dockerfile
FROM python:3.10

COPY . /src
RUN pip install /src
# ...
```

This would fail if `.git` is excluded from Docker build context, which I believe a common practice

**Comment by drewoldag** [comment]
Perhaps too niche. setuptools-scm is fairly integrated.
