### ISSUE TITLE
The license of this project

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#305]
The current `LICENSE` file contains BSD license. It is unclear if and how the output of the `copier` (aka user's project) should respect this license.

I believe that the legal usage of `python-project-template` requires a clarification, or we should change the license to public domain, for example via [CC0](https://creativecommons.org/public-domain/cc0/) or [Unlicense](https://en.wikipedia.org/wiki/Unlicense)

**Comment by drewoldag** [comment]
Talk to Andy, ask for legal assistance to determine what the appropriate license should be.

**Comment by drewoldag** [comment]
Sent an email to Andy and Laura Dorsey, UW's legal advisor when it comes to license stuff. I'll report back here with any feedback I receive.

**Comment by drewoldag** [comment]
After feedback from Laura and Andy, it sounds like sticking with the BSD license is ok based. I've copied over the last few back-and-forths here:

> [Laura] BSD is very permissive and the license we recommend for source code. It just requires a user of the code to attribute you if you inserted an attribution requirement. I see it was funded by the Schmidt Family foundation. That gift letter may specify what open source license we use. I don’t have an easy way to see gift letters.
> [Andy] Schmidt doesnt require one but we have used BSD for a long time and it works well so I would say we go with that. 

Based on this conversation, I'll think we'll stick with what we've got. If this doesn't actually address your concerns @hombit, please feel free to reopen this issue,
