### ISSUE TITLE
Ask user for GitHub repo link

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#307]
Currently, copier doesn't ask and doesn't know GitHub repo link. However it would be useful to have and use at least in two places:

- [ ] `asv.conf.json` needs it
- [ ] `pyproject.toml` should use it for `project.urls` to populate "Source Code" URL for PyPi

**Comment by hombit** [comment]
For pre-existing projects we can get it from git with something like `git remote get-url origin` and with a bit of parsing for ssh-based URLs.

**Comment by delucchi-cmu** [comment]
We could also include some badges on the README if we have the github URL at the template hydration stage.

**Comment by delucchi-cmu** [comment]
I'm thinking to instead just ask for the organization name, since that will help us to generate those badge URLs that aren't just appending to the base URL but perturb it in weird ways (that I'd prefer to have in the template than try to remember every time)

e.g.
```
https://github.com/{{project_organization}}/{{project_name}}
https://{{project_organization}}.github.io/{{project_name}}/
https://{{project_name}}.readthedocs.io/
https://codecov.io/gh/{{project_organization}}/{{project_name}}
```
