### ISSUE TITLE
Create a sidecar template that will help with conda installability

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#310]
There is potentially a lot here, on the surface the question is, "should we create, and maintain, a template that can be used in addition to the base PPT, that will provide more support for conda?" Some dependencies are not pip installable, and require using conda, so can we make that easier with for local use and CI? This could also be an opportunity to provide support for packages that are going to be published to conda-forge for installation via `conda install <superthing>`.

At a higher level, this is also a good time to think through how we would want to structure sidecar templates so that they can be easily integrated with the base template in the future. I don't know if we needed a metatemplate - a template for creating sidecar templates, but maybe at least some guidance :)

**Comment by drewoldag** [comment]
Related to #168

**Comment by delucchi-cmu** [comment]
> This could also be an opportunity to provide support for packages that are going to be published to conda-forge for installation via `conda install <superthing>`.

This is related to https://github.com/lincc-frameworks/python-project-template/issues/342

**Comment by delucchi-cmu** [comment]
Closed by #342
