### ISSUE TITLE
Change the "pylint or black" question.

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#311]
These two tools accomplish different goals. So it probably makes sense to remove the "choose 1) pylint 2) black 3) none" question, and replace it with something like: 
- black yes/no
- ruff yes/no
- pylint yes/no

**Comment by drewoldag** [comment]
This is related to issue #122

**Comment by delucchi-cmu** [comment]
This has been addressed with a multi-select question, enabling user to choose any of (ruff, pylint, black, or isort), and they can all interoperate in a single repo.
