### ISSUE TITLE
Cron dispatch workflows should send failure emails

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#312]
There are two default github workflows that run on a nightly basis: smoke test and nightly benchmarks.

If they fail, they'll only alert the person who set up the workflow (and possibly anyone following *all* repo activity?). I think it's possible to have a workflow step that will send an email in the event of failure.

We're already capturing an email (either single person or group alias) as part of template hydration.

**Comment by drewoldag** [comment]
This seems related to #293 in that the alert about a workflow going into hibernation mode is only sent to the person who created the action.

**Comment by drewoldag** [comment]
Alternatively (or in addition to) the email approach, we could stub in the thing that will emit a failure message to slack.

**Comment by delucchi-cmu** [comment]
```
How would you like to receive workflow failure notifications?
> email
  slack bot integration (additional configuration required)
  none
```
