### ISSUE TITLE
.prepare_project.sh parses Apple's Git version wrongly

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#327]
When I run `.prepare_project.sh` I see the following output:
```
Initializing local git repository
.prepare_project.sh: line 6: let: Git-143)<2: syntax error in expression (error token is ")<2")
.prepare_project.sh: line 9: let: Git-143)==2 & <34: syntax error in expression (error token is ")==2 & <34")
Installing package and runtime dependencies in local environment
Installing developer dependencies in local environment
Installing pre-commit
```

It is what I get if I run line 6 manually in my shell (tried both bash and zsh):
```sh
> echo $(git version | sed 's/^.* //;s/\./ /g')
Git-143)
```

I believe that the reason is that Apple's git (the one you get with Mac's command line tools / XCode) has the following version information:
```sh
> git version
git version 2.39.2 (Apple Git-143)
```

I believe that something like `git version | awk '{print $3}' | sed 's/\./ /g'` would work better here

**Comment by jeremykubica** [comment]
Fixed in #359
