### ISSUE TITLE
prepare_project.sh fails on older pip versions

### ISSUE THREAD

**Issue by talister** [lincc-frameworks/python-project-template#333]
Following the instructions for a new project fails at the `bash .prepare_project.sh` with older versions of `pip` as are standard on e.g. RockyLinux 9:
```
(lincc_venv) [lincc_example]$ bash .prepare_project.sh 
Initializing local git repository
Installing package and runtime dependencies in local environment
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/tlister/git/lincc_example
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the '/home/tlister/venv/lincc_venv/bin/python -m pip install --upgrade pip' command.
Installing developer dependencies in local environment
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/tlister/git/lincc_example
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the '/home/tlister/venv/lincc_venv/bin/python -m pip install --upgrade pip' command.
Installing pre-commit
.prepare_project.sh: line 25: pre-commit: command not found
```
Upgrading the initial version of `pip` in the virtualenv fixes this problem (I _think_ the behavior changed in `pip>=22.0` but the changelog is confusing) but an instruction to update `pip` should maybe be included - Rocky 9 is relatively new (July 2022 release) and is in theory supported out to 2032 (albeit probably not with the same `pip` version)

**Comment by drewoldag** [comment]
Could be faster to just check pip version and redirect to documentation if the pip version is too old. 

Also, we could expand prepare_project.sh so that's more self descriptive and would allow users to modify it to their liking.
