### ISSUE TITLE
On new project creation, prompt's example text is prepended to actual answers, prepare_project fails

### ISSUE THREAD

**Issue by ssteinerx** [lincc-frameworks/python-project-template#338]
I picked "simple", answered the questions and this is what the top of my pyproject.toml looked like  :
```
[project]
name = "example_projecttestproject"
license = {file = "LICENSE"}
readme = "README.md"
authors = [
    { name = "Your NamessteinerX", email = "name@you.comssteinerX@gmail.com" }
]
```
Attempting to run prepare_project.sh didn't go well with the first failure being that  "name@you.comssteinerX@gmail.com"  is not a valid email address and the rest was just a cascade from there.

**Comment by drewoldag** [comment]
Thanks for the heads up, and sorry that it caused you trouble! We'll be spending some time on Monday looking into this.

**Comment by delucchi-cmu** [comment]
I tried to re-create the behavior this morning, but was unable to. I suspect this is related to behavior within `copier` (the utility we use for prompts and hydrating the project based on the user's answers) or one of its upstream packages.

@ssteinerx - Do you mind sharing the versions you're working with?

```
$ pip show copier
Name: copier
Version: 9.0.1
...
$ pip show jinja2
Name: Jinja2
Version: 3.1.2
...
$ pip show prompt-toolkit
Name: prompt-toolkit
Version: 3.0.36
...
```

**Comment by ssteinerx** [comment]
Sorry, this environment no longer exists and I've moved too far past this brief experiment to recreate it.  I apologize for not including more version information to begin with, but I really wouldn't have known which versions of what were even relevant.

**Comment by jeremykubica** [comment]
I also tried to reproduce this and was not able.

**Comment by ssteinerx** [comment]
I'm going to pull the latest right now and see what I can see.

**Comment by ssteinerx** [comment]
Ok, I ran it, and got the version warning.  If I'm not mistaken, I was using Copier 9.0 when I did the original test:

```bash
copier copy python-project-template/ ppt-test1
...copier/lib/python3.12/site-packages/copier/template.py:134: OldTemplateWarning: This template was designed for Copier 8.0.0, but your version of Copier is 9.1.1. You could find some incompatibilities.
  warn(
🎤 Would you like to use simple (default tooling) or customized installation?
   simple
🎤 What is the name of your project?
   ss_test_example_project
🎤 What is your python package name?
   ss_test_example_package
🎤 What github organization will your project live under?
   ss_test_organization
🎤 What is the name of the code author? (Can be a person or organization)
   SS Tester
🎤 Code author's preferred email address?
   ss@tester.com
🎤 What license would you like to use?
   MIT
```
I searched through all of the files for "ss_test" and there was none of the "default value" + "_ss_test" stuff I was seeing before.

I was able to do this several times in a row previously and didn't have time to do other than get a quick issue out there.  It was so consistent, I figured it'd be easy to duplicate and the toolchain was current and freshly installed at the time.  

I'm going to chalk this up to a versionic mixed metaphor and close this issue.
