### ISSUE TITLE
I cannot import because exampke_benchmarks are missing

### ISSUE THREAD

**Issue by sylvielsstfr** [lincc-frameworks/python-project-template#351]
************* Module benchmarks.benchmarks
benchmarks/benchmarks.py:6:0: E0401: Unable to import 'example_benchmarks' (import-error)

I have fllowed the instructions to create a new project https://lincc-ppt.readthedocs.io/en/latest/source/new_project.html
(I already had done it previously many times after your presentation at DESC-sprint).

- I have first created new project on github
- I have created a new branch to incorporate the python project templates files
- I have done git clone and git checkout on the new branch
- I have run copier
-   I have done bash .prepare_project.sh
- I have done git add . and commit. 

the precommit fails because

But example_benchmark are missing ??

**Comment by drewoldag** [comment]
We're taking a look at this right now, and we'll post and update here when we find a root cause.

**Comment by camposandro** [comment]
Thanks @sylvielsstfr! I sent out a small patch to fix this and we will be publishing a new release very soon.
