### ISSUE TITLE
Continuous Integration Pre-Commit failed

### ISSUE THREAD

**Issue by mschwamb** [lincc-frameworks/python-project-template#357]
The Jupyter notebook in the template has no cells defined as it was never run. So we have pre-commit check failures because there was no output to remove. This was fixed by running the notebook and installing that. I am not sure if that's the best solution, but I wanted to raise it since it took a bit of time to realize why the CI checks/tests were failing on the pull request for the template.

**Comment by drewoldag** [comment]
Thanks for the heads up here @mschwamb! We'll take a look at this ASAP.

**Comment by jeremykubica** [comment]
Could it be failing because the default intro notebook does not have any ID strings for the later code blocks? They became required in a recent version of nbconvert. Perhaps we can get around the problem by manually adding ids to those cells.

**Comment by jeremykubica** [comment]
The following change gets rid of at least one error, but is still failing for me: https://github.com/lincc-frameworks/python-project-template/tree/issue/357/add_notebook_ids

**Comment by mschwamb** [comment]
I downloaded the notebook so each cell had a number and uploaded it back and then it worked. I think doing that adds ids to the cells

**Comment by drewoldag** [comment]
@mschwamb is there any chance that you might have copied the original error message that was being reported?
@jeremykubica any chance that you copied the secondary error message that was being reported? 

I've tested locally and it seems like things are working as expected when I use the change that Jeremy introduced (the extra cell ids) but I'm also not confident that I'm not just missing the use case that the two of you were seeing.

**Comment by jeremykubica** [comment]
I did not get an error message.  It just failed the step:
```
[INFO] This may take a few minutes...
Check template version...................................................Passed
- hook id: check-lincc-frameworks-template-version
- duration: 0.13s
Clear output from Jupyter notebooks......................................Failed
- hook id: jupyter-nb-clear-output
- files were modified by this hook

[NbConvertApp] Converting notebook docs/notebooks/intro_notebook.ipynb to notebook
[NbConvertApp] Writing 2191 bytes to docs/notebooks/intro_notebook.ipynb
```
I tried running it in debug mode, running "jupyter nbconvert" directly, and running it on a new (empty) project. But I wasn't able to get any more useful input.

Note that I've never directly run this step from my laptop before, so it could be failing due to something unrelated with my configuration.

**Comment by drewoldag** [comment]
I found a incorrect indent in one of the curly braces of the notebook. Once that was corrected, I was able to get precommit to run completely. 

For the record this was my manual testing script:

```
>> copier copy --vcs-ref=HEAD ./python-project-template/ ./science
# take the defaults for all the questions
>> scratch  # <- A custom script that creates an empty, "scratch" conda environment and activates it.
>> bash .prepare_project.sh
>> git checkout -b initial_branch
>> git add .
>> git commit -m 'initial commit'
# witness pre-commit pass all the hooks.
```
