### ISSUE TITLE
Upgrade actions before Node 16 reaches end of life

### ISSUE THREAD

**Issue by camposandro** [lincc-frameworks/python-project-template#358]
GitHub support for Node 16 is coming to an end this spring ([reference](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)) and we've been receiving warning in our workflows about it. We should upgrade the action versions to use Node 20. 

I gathered the following list of actions, but it may be incomplete:
- actions/checkout@v3 **to v4**
- actions/setup-python@v4 **to v5**
- actions/cache@v3 **to v4**
- peter-evans/find-comment@v2 **to v3**
- peter-evans/create-or-update-comment@v3 **to v4**
- pre-commit-ci/lite-action@v1.0.1 __(does not seem to have support yet)__

**Comment by delucchi-cmu** [comment]
Do we need to be using specific versions of the workflows, or could we specify `@main` and only pin to a specific version when necessary?
