### ISSUE TITLE
Create an example output repository after release v. 1.0.0 is created.

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#36]
It would be nice to have an example output from using the template as a parallel repo. 

It would be _really_ nice if someone who isn't related to the project were to do it. Just as a way to make sure that the project template works as expected. Look out for missing documentation, provide feedback, etc.

**Comment by drewoldag** [comment]
This is sort of related to #19 in that it could be used as a canary to ensure that various smoke tests and the like are working as expected. 

However, maintaining a separate repo like this becomes a developer burden, and could likely be replaced with links to the 2 minute video from the TVS meeting, as well as, later, the video from the LINCC tech talk where we present this template.

**Comment by dougbrn** [comment]
I'm probably only at like a 30% understanding level here as I'm a github actions novice, but [this post](https://blog.marcnuri.com/triggering-github-actions-across-different-repositories) highlights the use of the repository_dispatch event to trigger a workflow in another repository. So potentially if we had a template example repo, this could be used from the python-project-template repo (on a new push/or just release?) to trigger a "copier update -> commit/push" style workflow in the example repo

**Comment by drewoldag** [comment]
Sounds like this will be too much work to maintain, and all the branching options make it almost intractable.
