### ISSUE TITLE
Add documentation for github issue/PR templates

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#363]
- What makes a good issue template
- some examples
- how to order templates in the directory for UI ordering

**Comment by dougbrn** [comment]
I'm interested in this, will try to take a stab at creating an issue template with some accompanying docs for issue and PR templates. @delucchi-cmu I'm not quite sure if I understand the third bullet point, could you provide some more info on what you had in mind?

**Comment by dougbrn** [comment]
I may have a better understanding of point 3 after a little bit of tinkering, the question is just how to control the ordering of this page, right? 
![Screen Shot 2024-02-02 at 12 39 45 PM](https://github.com/lincc-frameworks/python-project-template/assets/8853505/1d8e2586-6f93-4d40-9dc4-bb4b3b110365)

**Comment by dougbrn** [comment]
Resolved by #376
