### ISSUE TITLE
Support pre/post text in copier flow

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#364]
I'm botching the description, but @drewoldag discovered a newly-released feature of copier adds pre- and post-question text to the prompts. We have a lot of help text currently on this help page (https://lincc-ppt.readthedocs.io/en/latest/source/new_project.html) that could be migrated to appear in the commandline while completing the copier questionnaire.

**Comment by drewoldag** [comment]
https://copier.readthedocs.io/en/stable/configuring/#message_after_copy

It supports jinja templating and will have the context of the generated project - so we could do something slick like print out the next steps for the user and they could be customized based on the responses that the user provided.
