### ISSUE TITLE
Add support for setuptools_scm so that we can pull version id from git scm.

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#37]
Expected behavior is that we should be able to create a new tag or release in GitHub, and that setuptools_scm would automatically populate a `_version.py` file with version information.

**Comment by delucchi-cmu** [comment]
I'm not sure that any steps are required. If a project is released in GitHub, setuptools_scm will provide a reasonable value with a simple API call; no _version.py file required.

```
from setuptools_scm import get_version
version_string = get_version()
```

**Comment by drewoldag** [comment]
So is it the case that all we need to do is add  `"setuptools_scm"` to the pyproject.toml file?

**Comment by drewoldag** [comment]
Also make sure that sphinx documentation grabs the correct version of the code using instructions here: https://github.com/pypa/setuptools_scm#usage-from-sphinx
