### ISSUE TITLE
Codecov CI action should install package in dev mode

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#381]
In current `main`, codecov action installs the user's package with `pip install .`. It looks like sometimes it may cause some issues with `pytest`, see this failed action ([corresponding workflow](https://github.com/lincc-frameworks/pandas-ts/blob/5632cbead96fd65d72d3ad125f450c8a013e5287/.github/workflows/testing-and-coverage.yml)):
https://github.com/lincc-frameworks/pandas-ts/actions/runs/7785027534/job/21226701366?pr=20

I'm not sure why it happens, it may be issue with my project. Shallow googling showed that maybe it is because `pytest` is unhappy with `pip install` which may leave some artifacts in the working directory. I solved the issue on my side changing both coe installation lines to
```sh
pip install -e .
pip install -e .[dev]
```

**Comment by hombit** [comment]
Actually it dev mode didn't solve my issue

https://github.com/lincc-frameworks/pandas-ts/actions/runs/7795789421/job/21259304324#step:6:1

**Comment by delucchi-cmu** [comment]
Based on my (very limited) experimentation, this looks more related to removing the `tests` argument to pytest, which YOU ASKED FOR.

https://github.com/lincc-frameworks/python-project-template/issues/249

https://github.com/lincc-frameworks/pandas-ts/pull/24/files
