### ISSUE TITLE
Feature request: pre-commit hook for CI workflow files

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#383]
Debugging GitHub actions is annoying, but hopefully we may help with it. It would be useful to have a `pre-commit` hook which would validate GitHub action files before we even push them. I've found this tool, but I'm not sure if it the only/best one:
https://github.com/mpalmer/action-validator

May be partially solved by implementing #382 instead

**Comment by camposandro** [comment]
There's also the `check-github-workflows` hook suggested by pre-commit's development team. It also seems to download GitHub workflows schema to perform this type of validation: 

https://github.com/lincc-frameworks/python-project-template/blob/b2bd2a02fe7637232ef8422c93b5fe51d22ab9b3/python-project-template/.pre-commit-config.yaml.jinja#L40-L45

**Comment by hombit** [comment]
Great, thank you!

**Comment by hombit** [comment]
Sorry, I shouldn't close it
