### ISSUE TITLE
pre-commit ruff hook name is misleading

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#384]
In current `main`, pre-commit ruff hook name is "Format and lint code using ruff". However the hook docs say that actually there are two different hooks (`ruff` and `ruff-format`) for linting and formatting:
https://github.com/astral-sh/ruff-pre-commit

Git blamed @smcguire-cmu, so I assign him to this issue

Side note: should I open a separate issue for having an option to set `ruff` to be a default formatter instead of `black`?

**Comment by drewoldag** [comment]
@hombit I would open a separate issue for setting `ruff` as the default formatted instead of `black`.

**Comment by drewoldag** [comment]
@smcguire-cmu it looks like you were assigned by default, do you have time to take this on? Feel free to say no :)
