### ISSUE TITLE
Ruff linter and ruff formatter conflict

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/python-project-template#409]
Currently, `pre-commit` runs `ruff` lints before `ruff-format`. This can be annoying when `pre-commit` is used to format the code because the linter may fail due to formatting issues (such as line length) before the formatter runs. I see two potential solutions:
1. Reorder the `ruff` and `ruff-format` hooks so that formatting occurs first.
2. Disable lint rules related to formatting issues.

**Comment by camposandro** [comment]
@hombit, ruff does not recommend ordering these hooks when using the linter with "--fix":

> When running with --fix, Ruff's lint hook should be placed before Ruff's formatter hook, and before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.

The formatter would help us to remove linting issues for some of the rules (e.g. line-too-long) but then we'd have to rerun the formatter after the linter to make sure its automatic changes didn't break the format. It's another kind of egg-chicken problem. Closing it for now!
