### ISSUE TITLE
Consider incorporating git-lfs for large file support

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#41]
The instructions here (https://git-lfs.com/) make it look like this would be a pretty straightforward operation to perform when the template is hydrated. We could add the `git lfs install` step as one of the "tasks" in `copier.yml`, and include a `.gitattributes` file in the template that includes some common file types. 

It would also be wise to add some documentation in the readme about what it is, why it's useful, and pointing to the git-lfs documentation. 

Extra bonus would be to make this an optional feature that that would be included by default. But I kind of like just making it available out of the box.

**Comment by drewoldag** [comment]
Here's a blog post that has an example `.gitattribute` file that we could use as a starting point: 

https://rehansaeed.com/gitattributes-best-practices/#git-large-file-system-lfs

I'm kind of surprised that there's not a "standard list" similar to the .gitignore list that seems to cover just about every case. But I suppose there are a lot more file types than I can imagine.

**Comment by cchris28** [comment]
I have found it most useful to add individually since what you consider an lfs extension can be project specific.
And remember that linux does not always use extensions. They have no intrinsic meaning.

**Comment by cchris28** [comment]
I do not think we want to enable this by default so I opted for a three way: not, commented example, and active example.
I also did not find a way to automatically install git-lfs. It turns out that the pypi package "git-lfs" is NOT git-lfs. What is up with that? So I opted for documentation.
