### ISSUE TITLE
updates to the documentation

### ISSUE THREAD

**Issue by biprateep** [lincc-frameworks/python-project-template#451]
Faced this issue while deploying a package, so thought it will be better to be explicit about this in the documentation for setting up PyPi (https://lincc-ppt.readthedocs.io/en/latest/practices/pypi.html). When creating a PyPI trusted publisher, there is a field name "Environment Name" which is optional and the website uses the environment name "release" in their demo. It turns out that it is better to leave that field empty rather than putting any random name over there. If empty PyPi does not care but if given a name, it has to match the environment that runs the action. It will be good to mention that in the documentation explicitly. i.e. leave the field name empty or use "XXXX" as the environment name.

**Comment by biprateep** [comment]
Secondly, it will also be good to add a page on how to add required dependencies to the project. I am trying to figure that out now and the first place I looked was the project template website but could not find that.

**Comment by biprateep** [comment]
I am now just using this thread to list down things I am encountering on my way.

It is pretty likely that the sphinx documentation will include references to published articles. It will therefore be useful to add this: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html#minimal-example as one of the extensions included with the sphinx installation. This gives a bibtex-style bibliography management system. I added it to my project and seems to be working well.

**Comment by drewoldag** [comment]
I've updated the documentation based on the first two comments. I'm going to leave out the sphinx example for the time being, just because that seems like the type of thing that should be fairly easy to look up in general. However, @biprateep if you disagree, and feel that it would be particularly valuable to include the citation example, please let me know!
