### ISSUE TITLE
Include link to PPT paper on PPT readme

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#454]
See https://iopscience.iop.org/article/10.3847/2515-5172/ad4da1

**Comment by rmandelb** [comment]
Besides including the link as a reference, we should add a specific request for people to cite it in their papers when making use of the template.

**Comment by hombit** [comment]
We could copy-paste bib-code from here to the readme
https://ui.adsabs.harvard.edu/abs/2024RNAAS...8..141O/exportcitation

**Comment by hombit** [comment]
Github docs about code citation
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
