### ISSUE TITLE
pipx installation

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/python-project-template#51]
Capturing some findings from freaky fixit + discussion w/drew:

* Hadn’t heard of pipx at all, probably the case for most users as well. Maybe a sentence or two explaining why it’s needed would be good.
* needed to run `pipx ensurepath`, to get copier working. Popped up as a warning when running, but may be worth an explicit warning in the docs for naive pipx users
* Question of if pipx is needed. It saves users from having to reinstall copier in every environment, but overhead of understanding pipx is present. One solution is to have the docs use pip, but have a callout/subsection that shows how one would use pipx for it's long-term benefits

**Comment by drewoldag** [comment]
If the answer to the last question is "No, we don't really need pipx" then the ticket changes to something more like "alter the README to indicate that the user should create a clean working environment, install copier, then run copier <blah>'.

**Comment by dougbrn** [comment]
Resolved in #82
