### ISSUE TITLE
Add a makefile into the docs

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/python-project-template#68]
A makefile should be present to allow users to build docs locally. Currently, if a user wanted to create one for the existing template, they'd likely have to copy one over and modify it as needed. We can protect from potential confusion by just having a predefined file ready to go.

One note, is that a default Makefile (e.g. one made by sphinx-quickstart) expects the documentation source files to live in a source directory. So this default should either be changed in the makefile, or the doc source files should be moved into a source/ folder. The advantage of the latter is that it seems more like the standard.

**Comment by drewoldag** [comment]
Adding the Makefile back should be pretty straightforward. I was already around in version 1.0.0 of the code. You can see it here: 
https://github.com/lincc-frameworks/python-project-template/blob/v1.0.0/python-project-template/docs/Makefile

But I removed it trying to clean up the documentation work without thinking clearly about it's necessity. 


WRT to the ./docs/source directory
I struggled to get sphinx builds working locally and on readthedocs, and through trial and error finally got it to work in the state that it's in now. However, it may be absolutely trivial to reintroduce the ./docs/source directory. Just be sure to test it both locally and in a real repository to make sure that it's working correctly.

**Comment by drewoldag** [comment]
Also if you want a gigantic gold star - remove the (I would call it hideous) CSS templating that is being used when published to read the docs. Currently it's using "Alabaster" when published to Readthedocs, but uses the standard readthedocs theme when published locally. 

And in case it's not clear, I really don't like the Alabaster theme. 

It should just be a matter of removing these lines: https://github.com/lincc-frameworks/python-project-template/blob/main/python-project-template/docs/conf.py.jinja#L51-L58

**Comment by delucchi-cmu** [comment]
To build locally, you can use the same commands that readthedocs uses:

$ python -m sphinx -T -E -b html -d _build/doctrees -D language=en . ../_readthedocs//html

One big benefit is that this will break in the same ways as when it fails on readthedocs. I'll add something in the docs about this.
