### ISSUE TITLE
Adjust line width in RST docs

### ISSUE THREAD

**Issue by delucchi-cmu** [lincc-frameworks/python-project-template#71]
Line width is all over the place.

**Comment by drewoldag** [comment]
@delucchi-cmu if you have a minute, coul you provide an example of where the line widths are no good, and perhaps an example of where they are so that whoever picks this up knows what it's suppose to look like?

**Comment by delucchi-cmu** [comment]
When I copied over README content, I didn't insert line breaks in the rst source files. At least in VSCode, it isn't wrapped reasonably when I have an editor open, and looks silly.

https://raw.githubusercontent.com/lincc-frameworks/python-project-template/main/docs/index.rst

For an example of run-on source lines.

https://raw.githubusercontent.com/LSSTDESC/RAIL/main/docs/source/citing.rst

For an example of wrapped source lines.

Ideally, this could be managed by an autoformatter, but I don't know of a good one for RST.
