### ISSUE TITLE
Investigate performance monitoring similar to codecov

### ISSUE THREAD

**Issue by drewoldag** [lincc-frameworks/python-project-template#79]
**Disclaimer** I don't know if this exists

It would be very nice if we could find something that will allow us to record the time to run a test as a proxy for code performance. 

Ideally this could be applied to the smoke test automation so that dormant projects will be monitored as well. 

The specific example where this would have been valuable:
The project `FlexCode` takes a dependency on `xgboost`, but didn't define the specific version of the dependency. 
The xgboost version was updated from 0.9 to 1.0, and that introduced a significant increase in `FlexCode` run times. 
This went completely unnoticed until someone asked, "hey isn't this taking a lot longer to run???" 
If there was a smoke test that recorded test run time in addition to pass/fail, then at least there would have been an indicator of the problem.

**Comment by delucchi-cmu** [comment]
I also haven't looked too much into the opensource/python options, but I know I've run into this problem elsewhere, and it's tricky. The best solution there was to use timeouts in your test suite, with per-test exceptions if you know it's going to be a longer-running test (e.g. sets up a lot of data).

If your test suite organically takes 5% longer each day, then an anomaly detection kinda suite would likely not notice that the test has grown prohibitively expensive. Having a timeout will raise errors when the test exceeds the threshold, so you'll at least find out then.

If your test is suddenly 200% slower, it could be a transient issue (in which case, just re-running would be preferred), or it's really a newly-introduced bug. If that 200% still falls under the timeout threshold, then you won't get notified, which is annoying, but also makes the case for some larger integration-style tests in your test suite.

I guess I had thought that timeouts were baked into pytest, but they're not and you'd need something like [pytest-timeout](https://pypi.org/project/pytest-timeout/) to accomplish this. But maybe this package would qualify as a best practice?

**Comment by delucchi-cmu** [comment]
I think I like where we "settled" on this today - we'll try out pytest-timeout in a few repos, and if we're happy with it, we can expand the usage to other repos (and probably the template).

**Comment by drewoldag** [comment]
pytest-timeout seems like a good option. Though it probably makes sense to try it out in a few repos locally before declaring it a best practice.

Also, unnervingly, the first line on PyPI for pytest-timeout is, "This is not the timeout you are looking for!"

**Comment by delucchi-cmu** [comment]
Dumping this note *somewhere*: pytest monitor creates a `.pymon` file that we should add to the `.gitignore` file in the template.

**Comment by delucchi-cmu** [comment]
This has been implemented and follow-up issues are being opened for bugs/features.
