### ISSUE TITLE
Test hydrated project GitHub workflows

### ISSUE THREAD

**Issue by smcguire-cmu** [lincc-frameworks/python-project-template#90]
Currently the only way to test the GitHub action workflows is to create a repository on GitHub to upload the hydrated template to. It could be useful to add some automated tests to confirm the workflows work correctly.

After briefly looking into this, I think there might be two ways that could work to run the workflows. First is making the workflows in the hydrated template a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). I think these can be [run in a CI step specifying a file path](https://stackoverflow.com/questions/64055230/nested-templates-calling-a-yaml-file-from-another-yaml-file-in-github-actions), so this may work.

Another way could be using the [act](https://github.com/nektos/act) command line tool to run the project actions.

**Comment by drewoldag** [comment]
This is interesting, so is the thought that the GitHub workflow actions in the hydrated project would actually be referenced to scripts contained in the template repository?

**Comment by smcguire-cmu** [comment]
Yes, that'd be one way of doing it, and that way we can have automated tests for the scripts. I think another option would be to try to use act in the CI workflow to test the hydrated workflows, which wouldn't require it, but I have no idea how easily act will run in an action.

**Comment by drewoldag** [comment]
Probably not a high priority right now. Need to continue to look for a good solution, but not necessarily applicable to the PPT.
